### ISSUE TITLE
oh boi he cant stop with the obf

### ISSUE THREAD

**Issue by AcaiBerii** [portablemc/portablemc#4]
Imagine obfuscatatatateeeeing a minecraft launcher lolxddddddddd
multimc is a better option 100%
portable mc flags my antivirus everywhere
lollxddddddddddd

**Comment by yeetedmeme** [comment]
thanks for the words of wisdom, i gotta write that down in a book

use multimc if you want, this program is for people who like the vanilla launcher
antivirus is cause microsoft is mad cuz bad since im not a million dollar corporation with licenses

as the the great man himself once said

"learn how to spell bruh" 
-Sun Tzu, Art Of War
